"""add_age_experience_fields

Revision ID: 94ac94ac6f26
Revises: 
Create Date: 2026-01-29 10:34:46.672887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94ac94ac6f26'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.add_column(sa.Column('birth_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('age', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('mlb_debut_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('years_experience', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('career_pa', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('career_ip', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.drop_column('career_ip')
        batch_op.drop_column('career_pa')
        batch_op.drop_column('years_experience')
        batch_op.drop_column('mlb_debut_date')
        batch_op.drop_column('age')
        batch_op.drop_column('birth_date')

    # ### end Alembic commands ###
