"""add_performance_indexes

Revision ID: e9187ef9eceb
Revises: 94ac94ac6f26
Create Date: 2026-01-29 21:49:57.984900

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9187ef9eceb'
down_revision: Union[str, Sequence[str], None] = '94ac94ac6f26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.create_index('ix_players_consensus_rank', ['consensus_rank'], unique=False)
        batch_op.create_index('ix_players_draft_status', ['is_drafted', 'drafted_by_team_id'], unique=False)
        batch_op.create_index('ix_players_is_drafted', ['is_drafted'], unique=False)
        batch_op.create_index('ix_players_is_injured', ['is_injured'], unique=False)
        batch_op.create_index('ix_players_is_prospect', ['is_prospect'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.drop_index('ix_players_is_prospect')
        batch_op.drop_index('ix_players_is_injured')
        batch_op.drop_index('ix_players_is_drafted')
        batch_op.drop_index('ix_players_draft_status')
        batch_op.drop_index('ix_players_consensus_rank')

    # ### end Alembic commands ###
